// Writes seeds/demo/xii-scale.json, the 100-Participant XII demo (ticket 106): `pnpm tsx scripts/xii-scale-seed.ts`.
import { writeFileSync } from "node:fs";
import path from "node:path";

// Made-up names only: a given name and an object noun, never a real person.
const FIRST = [
  "Ada",
  "Bo",
  "Cass",
  "Dot",
  "Eli",
  "Fay",
  "Gus",
  "Hal",
  "Ivy",
  "Jax",
  "Kit",
  "Lou",
  "Mo",
  "Nell",
  "Otto",
  "Pia",
  "Quin",
  "Rex",
  "Sid",
  "Tess",
  "Uma",
  "Vic",
  "Wren",
  "Xan",
  "Yara",
  "Zed",
  "Abe",
  "Bea",
  "Cy",
  "Dee",
  "Eve",
  "Finn",
  "Gia",
  "Hux",
  "Ike",
  "Jo",
  "Kai",
  "Lia",
  "Max",
  "Noa",
  "Oz",
  "Peg",
  "Ray",
  "Sky",
  "Tal",
  "Ugo",
  "Val",
  "Wes",
  "Xia",
  "Yul",
  "Zoe",
  "Ari",
  "Bix",
  "Cleo",
  "Dax",
  "Esme",
  "Flo",
  "Gil",
  "Hana",
  "Ira",
  "Jem",
  "Kip",
  "Lark",
  "Mae",
  "Ned",
  "Ora",
  "Pax",
  "Rio",
  "Sol",
  "Teo",
  "Una",
  "Vin",
  "Wim",
  "Yves",
  "Zuri",
  "Arlo",
  "Bram",
  "Cal",
  "Dov",
  "Edie",
  "Fen",
  "Gem",
  "Hob",
  "Isla",
  "Jude",
  "Koa",
  "Lev",
  "Mira",
  "Nico",
  "Odo",
  "Pim",
  "Roo",
  "Suki",
  "Tam",
  "Ulla",
  "Vera",
  "Wynn",
  "Yuki",
  "Zev",
  "Ola",
];
const LAST = [
  "Anvil",
  "Banner",
  "Comet",
  "Dynamo",
  "Ember",
  "Falcon",
  "Gadget",
  "Harbor",
  "Ion",
  "Jetpack",
  "Kestrel",
  "Lantern",
  "Magnet",
  "Nebula",
  "Orbit",
  "Pixel",
  "Quasar",
  "Rocket",
  "Sprocket",
  "Turbine",
  "Umbra",
  "Vortex",
  "Widget",
  "Xenon",
  "Yonder",
  "Zeppelin",
  "Acorn",
  "Bellows",
  "Cobalt",
  "Domino",
  "Eclipse",
  "Fathom",
  "Geyser",
  "Halyard",
  "Igloo",
  "Jigsaw",
  "Kazoo",
  "Lagoon",
  "Mosaic",
  "Nimbus",
  "Oboe",
  "Pinwheel",
  "Quiver",
  "Ripple",
  "Saffron",
  "Tinsel",
  "Ukulele",
  "Velvet",
  "Walrus",
  "Yodel",
  "Zigzag",
  "Abacus",
  "Bramble",
  "Cactus",
  "Dirigible",
  "Easel",
  "Fiddle",
  "Gondola",
  "Hammock",
  "Inkwell",
  "Juniper",
  "Kettle",
  "Lollipop",
  "Marmalade",
  "Nutmeg",
  "Origami",
  "Pretzel",
  "Quokka",
  "Rhubarb",
  "Snorkel",
  "Teapot",
  "Upbeat",
  "Vanilla",
  "Waffle",
  "Yak",
  "Zucchini",
  "Accordion",
  "Biscuit",
  "Crumpet",
  "Doodle",
  "Eggnog",
  "Flapjack",
  "Gumdrop",
  "Hiccup",
  "Icicle",
  "Jellybean",
  "Kumquat",
  "Limerick",
  "Muffin",
  "Noodle",
  "Ocelot",
  "Parsnip",
  "Quibble",
  "Radish",
  "Sundial",
  "Thimble",
  "Unicycle",
  "Vole",
  "Wombat",
  "Yo-yo",
];

/** Two long made-up names, to see how lists truncate. */
const LONG = new Map([
  [7, "Maximiliana Featherstonehaugh-Quicksilver"],
  [42, "Bartholomew Thistlewaite-Underhill the Third"],
]);

/** The Hosts: a handful on @jahnelgroup.com, plainly fictional. */
const HOST_INDEXES = [16, 21, 63, 90];

const participants = FIRST.map((first, i) => {
  const displayName = LONG.get(i) ?? `${first} ${LAST[i]}`;
  const local = displayName
    .toLowerCase()
    .replace(/[^a-z]+/g, ".")
    .replace(/^\.|\.$/g, "");
  const domain = HOST_INDEXES.includes(i) ? "jahnelgroup.com" : "example.com";
  return {
    displayName,
    email: `${local}@${domain}`,
    ...(i % 9 === 0 ? { companyTag: "Contractor" } : {}),
  };
});

const names = participants.map((p) => p.displayName);
const slug = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
const doc = (text: string) => ({
  type: "doc",
  content: [{ type: "paragraph", content: [{ type: "text", text }] }],
});

// Step Challenge: every Participant, by steps (higher is better), with a
// tie at 10th.
const steps = names.map((name, i) => ({
  name,
  score: 182_000 - ((i * 7919) % 100) * 1_500,
}));
steps.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name));
steps[10].score = steps[9].score;
let place = 0;
const placements = steps.map((row, i) => {
  if (i === 0 || row.score !== steps[i - 1].score) place = i + 1;
  return {
    key: `step-challenge-${slug(row.name)}`,
    competition: "Step Challenge",
    participant: row.name,
    place,
    score: row.score,
  };
});

const organizer = "demo-organizer@jahnelgroup.com";

const seed = {
  edition: "xii",
  editionNumber: 12,
  year: 2027,
  startDate: "2027-02-21",
  endDate: "2027-02-26",
  storyTheme: "No Teams. Just You. All Hundred of You.",
  status: "live",
  mode: "free-for-all",
  teamLabel: "Team",
  leaderTitle: "Captain",
  slackChannelUrl: "https://jahnelgroup.slack.com/archives/war-week-xii",
  primary: "#c2185b",
  primaryForeground: "#ffffff",
  accent: "#2f4fd8",
  background: "#ffffff",
  foreground: "#111111",
  fontPreset: "sans",
  organizers: [],
  highlights: [],
  days: [
    {
      date: "2027-02-21",
      dayTheme: "Kickoff",
      scheduleItems: [
        { startTime: "09:00", title: "Opening breakfast", category: "meal" },
        {
          startTime: "10:00",
          endTime: "17:00",
          title: "Step Challenge starts",
          category: "competition",
          competition: "Step Challenge",
        },
        {
          startTime: "13:00",
          endTime: "17:00",
          title: "Ping Pong Bracket, Round 1",
          category: "competition",
          competition: "Ping Pong Bracket",
          location: "Game room",
        },
      ],
    },
    {
      date: "2027-02-22",
      dayTheme: "Head Start",
      scheduleItems: [
        {
          startTime: "08:00",
          endTime: "08:30",
          title: "Morning Stretch",
          category: "competition",
          competition: "Morning Stretch",
          location: "Main room",
        },
        {
          startTime: "12:00",
          endTime: "13:00",
          title: "Lunch: tacos",
          category: "meal",
        },
        {
          startTime: "13:00",
          endTime: "17:00",
          title: "Cornhole open play",
          category: "competition",
          competition: "Cornhole",
          location: "Out back",
        },
      ],
    },
    {
      date: "2027-02-23",
      dayTheme: "Midweek Rally",
      scheduleItems: [
        {
          startTime: "08:00",
          endTime: "08:30",
          title: "Morning Stretch",
          category: "competition",
          competition: "Morning Stretch",
          location: "Main room",
        },
        {
          startTime: "15:00",
          endTime: "17:00",
          title: "Darts throw-off",
          category: "competition",
          competition: "Darts",
          location: "Game room",
        },
      ],
    },
    {
      date: "2027-02-24",
      dayTheme: "Final Push",
      scheduleItems: [
        {
          startTime: "18:00",
          endTime: "20:00",
          title: "Trivia Night",
          category: "competition",
          competition: "Trivia Night",
          location: "Main room",
        },
      ],
    },
    {
      date: "2027-02-26",
      dayTheme: "Finale",
      scheduleItems: [
        {
          startTime: "16:00",
          title: "Closing ceremonies",
          category: "social",
          location: "Main room",
        },
      ],
    },
  ],
  participants,
  competitions: [
    {
      name: "Step Challenge",
      scoring: "individual",
      description:
        "Log your steps all week. Every one of the hundred is on the sheet; the top ten take Placement Points.",
      scoreDirection: "higher",
      placementPoints: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
      finalized: true,
      finalizedAt: "2027-02-23T09:00:00-05:00",
      finalizedByEmail: organizer,
    },
    {
      name: "Trivia Night",
      scoring: "individual",
      description: "Pub trivia, solo. Nobody's on the sheet yet.",
      placementPoints: [5, 3, 1],
    },
    {
      name: "Ping Pong Bracket",
      scoring: "individual",
      format: "bracket",
      bracketConfig: {
        entrantsPerHeat: 2,
        advancePerHeat: 1,
        thirdPlaceGame: true,
      },
      placementPoints: [8, 5, 3, 1],
      description:
        "Sixty-four players, single elimination, with a 3rd place game.",
    },
    {
      name: "Morning Stretch",
      scoring: "individual",
      format: "participation",
      participationPoints: 1,
      selfCheckIn: true,
      description: "Show up, stretch, get a point.",
    },
    {
      name: "Cornhole",
      scoring: "individual",
      format: "head-to-head",
      gameConfig: { drawsAllowed: false, bestOf: null },
      entrantsOpen: true,
      placementPoints: [5, 3, 1],
      description: "Log a Game whenever the boards are free.",
    },
    {
      name: "Darts",
      scoring: "individual",
      format: "best-score",
      gameConfig: { count: "best", betterIs: "higher", unit: "points" },
      entrantsOpen: true,
      placementPoints: [5, 3, 1],
      description: "Three darts a turn; your best turn counts.",
    },
  ],
  discretionaryPoints: [
    [3, "Ran the snack table all week"],
    [12, "Fixed the projector before the Finale"],
    [27, "Best costume on theme day"],
    [7, "Organized the carpool"],
    [55, "Helped judge Trivia Night"],
    [81, "Kept the Step Challenge leaderboard honest"],
  ].map(([i, reason], n) => ({
    key: `scale-discretionary-${n + 1}`,
    participant: names[i as number],
    points: 2,
    reason,
    enteredByEmail: organizer,
    enteredAt: `2027-02-2${2 + (n % 3)}T12:00:00-05:00`,
  })),
  placements,
  awards: [
    {
      key: "scale-mvp",
      name: "War Week MVP",
      participants: [names[3]],
    },
    {
      key: "scale-spirit",
      name: "Spirit Award",
      participants: [names[12], names[42]],
    },
  ],
  announcements: [
    {
      key: "scale-welcome",
      title: "Welcome, all hundred of you",
      pinned: true,
      authorEmail: organizer,
      publishedAt: "2027-02-21T08:00:00-05:00",
      body: doc(
        "A hundred Participants, no Teams. Check the Standings and log your Games from your phone.",
      ),
    },
  ],
  faqItems: [
    {
      question: "How do I get points?",
      answer: doc("Compete in anything on the schedule; every point is yours."),
    },
  ],
  finaleSlides: [
    { kind: "title" },
    { kind: "numbers" },
    { kind: "awards" },
    { kind: "champions" },
    { kind: "standings" },
    { kind: "winner" },
  ],
};

writeFileSync(
  path.resolve(process.cwd(), "seeds/demo/xii-scale.json"),
  `${JSON.stringify(seed, null, 2)}\n`,
);
